Work around a tag fetching problem
The workflow was triggering the error:
  Error: fatal: Cannot fetch both <sha> and refs/tags/<tag> to refs/tags/<tag>
so this is an attempt at a workaround.